version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
